export const DEFAULT_PLAYLIST = [
    "https://youtu.be/p6xqKJqsQWs?si=pmhPrEr2-MF0IofE",
    "https://youtu.be/oaIJNOqY1oQ?si=bfzjRfR751unUU4r",
    "https://youtu.be/nhAR2-WIM-I?si=G5UtEE9Ku1fuoQr7",
    "https://youtu.be/IHLLYeFc5sg?si=76HEFFNppRPIIFgo",
    "https://youtu.be/rJVYb2Ib8DU?si=Si9I2XcfXENpN2Jf",
    "https://youtu.be/Xc1Le3CSdrM?si=XFF1bkMhJyW6uJ73",
    "https://youtu.be/oaIJNOqY1oQ?si=Y5IlwlLIRRj5t76j",
    "https://youtu.be/-3CDcU-eco8?si=QLWIG1KEtX8x-d8p",
    "https://youtu.be/9pdi1twTpAs?si=Y8SFHDu968HK15yY",
    "https://youtu.be/IHLLYeFc5sg?si=nOv29DWKhj4DaYHd",
    "https://youtu.be/2mRKDQ0h1ao?si=vv4nj0MTSyk9g08U",
    "https://youtu.be/Im2Ord5fMu0?si=pVPIp-2ygmunYTL-",
    "https://youtu.be/DrKcJXKiVnA?si=1JWrfZSnDSgKhcnF",
];